# -*- coding: utf-8 -*-
"""model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aF6HNReu1Vvy-itNxjBO4dtNPH3MHHEr
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from google.colab import files

uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

df['LABEL'] = df['LABEL'].map({
    'non-sarcastic': 0,
    'sarcastic': 1
})

def clean_text(text):
    text = text.lower()   # only lowercase
    return text

df['clean_text'] = df['TEXT'].apply(clean_text)

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['LABEL'],
    test_size=0.2,
    random_state=42,
    stratify=df['LABEL']
)

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)   # improves sarcasm detection
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "SVM": LinearSVC(),
    "Random Forest": RandomForestClassifier(n_estimators=100)
}

results = []

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    preds = model.predict(X_test_vec)

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds)
    rec = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)

    results.append([name, acc, prec, rec, f1])

results_df = pd.DataFrame(
    results,
    columns=["Model","Accuracy","Precision","Recall","F1 Score"]
)

print(results_df)

results_df.to_csv("model_results.csv", index=False)
files.download("model_results.csv")

plt.figure(figsize=(10,6))
results_df.set_index("Model").plot(kind='bar')

plt.title("Traditional Models Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)

plt.savefig("traditional_models_bar.png", dpi=300, bbox_inches='tight')
plt.show()

files.download("traditional_models_bar.png")

best_model = results_df.sort_values(by="F1 Score", ascending=False).iloc[0]

labels = ["Accuracy", "Precision", "Recall", "F1 Score"]
values = best_model[["Accuracy","Precision","Recall","F1 Score"]]

plt.figure(figsize=(6,6))
plt.pie(values, labels=labels, autopct='%1.1f%%')
plt.title(f"Best Model: {best_model['Model']}")

plt.savefig("best_traditional_model.png", dpi=300)
plt.show()

files.download("best_traditional_model.png")

!pip install transformers datasets

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from google.colab import files

uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

df['LABEL'] = df['LABEL'].map({'non-sarcastic':0, 'sarcastic':1})

# Only lowercase (DO NOT remove punctuation)
df['clean_text'] = df['TEXT'].str.lower()

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['LABEL'],
    test_size=0.2,
    random_state=42,
    stratify=df['LABEL']
)

tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k,v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = Dataset(train_encodings, y_train)
test_dataset = Dataset(test_encodings, y_test)

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=2
)

training_args = TrainingArguments(
    output_dir='./bert_results',
    num_train_epochs=4,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_strategy="epoch"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=1)
labels = predictions.label_ids

accuracy = accuracy_score(labels, preds)
precision = precision_score(labels, preds)
recall = recall_score(labels, preds)
f1 = f1_score(labels, preds)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

bert_results = pd.DataFrame([[
    "BERT", accuracy, precision, recall, f1
]], columns=["Model","Accuracy","Precision","Recall","F1 Score"])

bert_results.to_csv("bert_results.csv", index=False)
files.download("bert_results.csv")

cm = confusion_matrix(labels, preds)

plt.imshow(cm)
plt.title("BERT Confusion Matrix")
plt.colorbar()

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.savefig("bert_confusion_matrix.png")
plt.show()

files.download("bert_confusion_matrix.png")

labels_chart = ["Accuracy","Precision","Recall","F1 Score"]
values = [accuracy, precision, recall, f1]

plt.figure(figsize=(6,6))
plt.pie(values, labels=labels_chart, autopct='%1.1f%%')
plt.title("BERT Performance")

plt.savefig("bert_pie_chart.png")
plt.show()

files.download("bert_pie_chart.png")

from google.colab import files

uploaded = files.upload()

import pandas as pd

results_df = pd.read_csv("model_results.csv")
bert_results = pd.read_csv("bert_results.csv")

final_results = pd.concat([results_df, bert_results])

print("Final Model Comparison:\n")
print(final_results)

final_results.to_csv("final_comparison_table.csv", index=False)

from google.colab import files
files.download("final_comparison_table.csv")

import matplotlib.pyplot as plt

# Set Model as index
final_results.set_index("Model", inplace=True)

plt.figure(figsize=(12,6))
final_results.plot(kind='bar')

plt.title("Comparison of Traditional Models vs BERT")
plt.ylabel("Score")
plt.xlabel("Models")
plt.xticks(rotation=0)
plt.legend(loc='lower right')

# Save graph
plt.savefig("final_comparison_bar.png", dpi=300, bbox_inches='tight')

# Show graph
plt.show()

# Download graph
files.download("final_comparison_bar.png")

